### ISSUE TITLE
Extension not updating....

### ISSUE THREAD

**Issue by ansanyyi** [mihonapp/mihon#186]
### Steps to reproduce

1. Click update
2. nothing happen

### Expected behavior

should've been updated

### Actual behavior

not updating 

### Mihon version

beta r6458

### Android version

Android 13

### Device

Redmi 10c

### Other details

MIUI optimization must be disabled to install extension.... already disabled it and still doesn't fix the problem
 
![Screenshot_2024-01-22-16-40-03-023_eu kanade tachiyomi j2k](https://github.com/mihonapp/mihon/assets/110255796/22a9ec10-83cd-4034-898a-e966f22a8125)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
That's not Mihon

**Comment by Dunky13** [comment]
@AntsyLich the screenshot is not Mihon, but sadly I am experiencing a similar issue on Mihon 0.16.1

**Comment by AntsyLich** [comment]
Yeah well fixed by cb068984303f811692531bf6f14902ae118d8ac7

**Comment by Dunky13** [comment]
Awesome! Thank you! 🙏

**Comment by ccrowles** [comment]
I'm still having this issue on Mihon 0.16.3 (stable). I had the extensions originally installed from Tachiyomi J2K, but since they couldn't be updated, I switched to Mihon. But when I tap the update button in the extensions list on mihon, and then the install button, nothing happens.

I use an old tablet of mine to read on Tachiyomi (Mi Pad 4, because 6 inches screen is the perfect size for me) so it still runs Android 8.1.0, MIUI 10 9.8.29 beta.
I have already disabled MIUI optimization in developer settings.

**Comment by CrepeTF** [comment]
> I'm still having this issue on Mihon 0.16.3 (stable). I had the extensions originally installed from Tachiyomi J2K, but since they couldn't be updated, I switched to Mihon. But when I tap the update button in the extensions list on mihon, and then the install button, nothing happens.
> 
> I use an old tablet of mine to read on Tachiyomi (Mi Pad 4, because 6 inches screen is the perfect size for me) so it still runs Android 8.1.0, MIUI 10 9.8.29 beta.
> I have already disabled MIUI optimization in developer settings.

You should probably uninstall those extensions if they came from before tachiyomi closed down. 

The apps use Tachiyomi's signature so they can only be updated by tachiyomi. It's an android security feature to not allow nefarious apps to overwrite legitimate ones.

**Comment by ccrowles** [comment]
Oh that's why, yeah reinstalling worked, thank you!
