### ISSUE TITLE
Tracker not working

### ISSUE THREAD

**Issue by Ubada03** [mihonapp/mihon#251]
### Steps to reproduce

I can't connect my myanimelist account.
I go to settings=>Tracking. 
Tap on MyAnimeList.
It takes me to browser and I put my username and password but it just shows the same tab again

### Expected behavior

It should login

### Actual behavior

It doesn't login

### Mihon version

0.16.1

### Android version

13

### Device

Oppo F21 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by DestroyerAce** [comment]
MAL tracker API wasn't configured properly in old mihon releases but its been fixed in the latest stable release(0.16.2) which you can download from the [releases section](https://github.com/mihonapp/mihon/releases/latest).
After installing the latest version all you need to do is relogin in MAL tracker and it should work.

**Comment by WGmg23** [comment]
is down

**Comment by oishi13chan** [comment]
I am using 0.16.3v and yet this issue isn't solved. Still can't log in to MAL or any other tracker.

**Comment by DestroyerAce** [comment]
https://github.com/mihonapp/mihon/issues/298

**Comment by Yootz** [comment]
> I am using 0.16.3v and yet this issue isn't solved. Still can't log in to MAL or any other tracker.

Same

**Comment by JustAnAmbler** [comment]
> I am using 0.16.3v and yet this issue isn't solved. Still can't log in to MAL or any other tracker.

Only MAL is broken now, Anilist and MangaUpdates are working as usual for me

**Comment by MajorTanya** [comment]
> > I am using 0.16.3v and yet this issue isn't solved. Still can't log in to MAL or any other tracker.
> 
> Only MAL is broken now, Anilist and MangaUpdates are working as usual for me

I literally just said this is a duplicate of #298 and you should stop commenting
