### ISSUE TITLE
The app is slow after preview r6654 (Samsung S9 plus/Android 10)

### ISSUE THREAD

**Issue by vagabondshrimp** [mihonapp/mihon#784]
### Steps to reproduce

1. Updating 
2. Restart phone
3. Uninstall
4. Clean install with no extensions

The issue persists

### Expected behavior

Screen records of preview r6654  mihon-arm64-v8a-r6654.apk

https://github.com/mihonapp/mihon/assets/74079735/10468093-796f-490c-9aef-ee1295e81b6b

https://github.com/mihonapp/mihon/assets/74079735/8b6ab407-56fb-481c-9e8c-f3c4eea48fad

The app works fine with no issue

### Actual behavior

Screen records of preview r6685  mihon-arm64-v8a-r6685.apk  (the same with r6674) 

https://github.com/mihonapp/mihon/assets/74079735/c6f56a3a-38dd-444e-b365-d1632efd7fd4 

https://github.com/mihonapp/mihon/assets/74079735/774fb270-767f-4176-8026-0f185e7cd362

As you can see, it's lagging/slow.

### Mihon version

Mihon preview r6685

### Android version

Android 10

### Device

Samsung S9 plus

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by momoe** [comment]
Samsung Galaxy S10 here in Android v10. Experience crippling UI lag

**Comment by FooIbar** [comment]
Should be fixed in Compose `1.7.0-beta01` (probably in the next preview).

**Comment by vagabondshrimp** [comment]
In preview r6697 the lag is mostly gone, but some is still present when opening a manga.
I can provide video recording if required.

**Comment by ken-tn** [comment]
Using preview r6793 this no longer occurs (Galaxy S9+).
Issue can be closed.
